name: Metrics
on:
  # Runs once a day at 03:00 UTC
  schedule: [{ cron: "0 3 * * *" }]
  # And you can also trigger it manually
  workflow_dispatch:

permissions:
  contents: write   # allow committing the SVG to your repo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🧮 Generate metrics
        uses: lowlighter/metrics@latest
        with:
          # Your GitHub username
          user: YOUR_USERNAME
          # The token you will add in step 3
          token: ${{ secrets.METRICS_TOKEN }}

          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Amsterdam

          filename: github-metrics.svg

          # Plugins you want
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_indepth: yes
          plugin_languages_sections: most-used
          plugin_languages_details: lines, percentage
          plugin_languages_threshold: 0%

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_habits: yes
          plugin_habits_days: 14
          plugin_habits_charts: yes
          plugin_repositories: yes
